### PR TITLE
Consolidates all mcp tools to take frameworks as arguments

### LINKED ISSUE #101: MCP consolidation
### Which project does this relate to?

Create Tanstack App

### Describe the bug

We currently have four tools that we expose using MCP. Two for React and two for Solid. Can we just make the framework an argument and go back to two?

### Your Example Website or App

https://github.com/TanStack/create-tsrouter-app

### Steps to Reproduce the Bug or Issue

1. Install the MCP server with:

```json
{
  "mcpServers": { 
     "create-tsrouter-app": {
         "command": "npx", 
         "args": [ "create-tsrouter-app@latest", "--mcp"]
     }
   }
}
```

Notice that there are four tools.

### Expected behavior

There should be two tools.

Also, we should look at the potential of using an MCP resource for documentation on how to use the tools. I'm not sure if VS Code, Windsurf and/or Cursor support it. It would be good to look into it.

### Screenshots or Videos

_No response_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rachelnabors**
This PR makes the MCP tools work across frameworks, reducing the number of tools an agent needs to create Tanstack applications. This is important because Agents work better with 5-6 tools. (Two for every JS framework isn't ideal!)
image

Closes #101

### CODE REVIEW

**Review by jherr — APPROVED** [review]

File: frameworks/react-cra/src/index.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export function createFrameworkDefinition(): FrameworkDefinition {
 
   return {
     id: 'react-cra',
-    name: 'react',
+    name: 'React',
```
Comment (DogPawHat) [inline frameworks/react-cra/src/index.ts:27]: This is the cause of https://github.com/TanStack/create-tsrouter-app/issues/119 

We're passing in lower case 'react' into the `getFrameworkByName` function and it breaks because it's case senstive.

**Comment by oliviermtl** [comment]
Mind blowing reactivity guys. Highly appreciated ❤️
